# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160207_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'branches'},
        ),
        migrations.AlterField(
            model_name='platform',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Device'),
        ),
    ]
