# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(default='0.0.0', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(default='0.0.0', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TargetPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Browser')),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.OperatingSystem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='page',
            old_name='creation_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='creation_date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='page',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.CharField(default='0.0.0', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='target_platforms',
            field=models.ManyToManyField(to='projects.TargetPlatform'),
        ),
    ]
