# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20160124_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='target_platforms',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='targetplatform',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='targetplatform',
            name='device',
        ),
        migrations.RemoveField(
            model_name='targetplatform',
            name='operating_system',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='TargetPlatform',
        ),
    ]
