# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 19:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_auto_20160124_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.CharField(blank=True, default='0.0.0', max_length=200, null=True)),
                ('screen_width', models.IntegerField()),
                ('screen_height', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.CharField(max_length=2083)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.CharField(blank=True, default='0.0.0', max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TargetPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='browser',
            name='version',
            field=models.CharField(blank=True, default='0.0.0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='version',
            field=models.CharField(blank=True, default='0.0.0', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='targetplatform',
            name='browser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Browser'),
        ),
        migrations.AddField(
            model_name='targetplatform',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Device'),
        ),
        migrations.AddField(
            model_name='targetplatform',
            name='operating_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.OperatingSystem'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_platforms',
            field=models.ManyToManyField(to='projects.TargetPlatform'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
