# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import private_media.storages
import projects.models
import uuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20160124_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(storage=private_media.storages.PrivateMediaStorage(), upload_to=projects.models.screenshot_upload_to)),
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('name', 'project')]),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('name', 'user')]),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Page'),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='target_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.TargetPlatform'),
        ),
    ]
