# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20160125_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='page',
        ),
        migrations.RemoveField(
            model_name='screenshot',
            name='target_platform',
        ),
        migrations.DeleteModel(
            name='Screenshot',
        ),
    ]
