# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import private_media.storages
import projects.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20160125_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(storage=private_media.storages.PrivateMediaStorage(), upload_to=projects.models.screenshot_upload_to)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Page')),
                ('target_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.TargetPlatform')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
