# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
