# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='browser',
            name='name_slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='name_slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='name_slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='name_slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='name_slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screenshot',
            name='name_slug',
            field=models.SlugField(default='defau;t\x08\x08lt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='targetplatform',
            name='name_slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('name_slug', 'project')]),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('name_slug', 'user')]),
        ),
    ]
