# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20160202_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='version',
            field=models.CharField(blank=True, default='0.0.0', max_length=200, null=True),
        ),
    ]
