# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20160204_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='version',
        ),
    ]
